# Generated by Django 2.2.3 on 2019-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCrudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_on',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
