# Generated by Django 2.2.3 on 2019-07-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoCrudApp', '0003_auto_20190729_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
